categories:
  - 'the-thao'
  - 'thoi-su'
  - 'the-gioi'
  - 'phap-luat'
  - 'kinh-doanh'
  - 'van-hoa'
  - 'suc-khoe'
  - 'khoa-hoc'
  - 'giai-tri'
  - 'giao-duc'
  - 'xe'

labels:
  - 'thế giới'
  - 'thời sự'
  - 'thể thao' 
  - 'kinh doanh'
  - 'pháp luật'
  - 'sức khỏe'
  - 'giáo dục'
  - 'văn hóa'
  - 'giải trí'

max_seq_len: 256

paths:
  sqlite_db: 'data/db.sqlite3'
  stopwords: 'data/stopwords/stopwords.txt'
  phobert_bpe: 'data/PhoBERT_base_transformers/bpe.codes'
  phobert_config: 'data/PhoBERT_base_transformers/config.json'
  phobert_dict: 'data/PhoBERT_base_transformers/dict.txt'
  phobert_model: 'data/PhoBERT_base_transformers/model.bin'
  phobert_base: 'data/phobert-base'
  vncoreNLP: 'data/vncorenlp/VnCoreNLP-1.1.1.jar'
